### PR TITLE
some functionality about socket io

### PR DESCRIPTION
**Pull request by dafeizizhu**
Signed-off-by: maizhiying zhiying.mai@gmail.com

### CODE REVIEW

**Comment by fuqcool** [comment]
That's Awesome!

It will be great if
A. indentation is two spaces
B. there are no semicolon at the end of each statement

Maybe we need a linter?

**Comment by dafeizizhu** [comment]
Please give me a sublime plugin to format and prettify.

P.S. I see the origin code use four spaces indenting and no semicolon, so I do the same thing o(╯□╰)o

**Comment by fuqcool** [comment]
sublime sucks!

**Comment by fuqcool** [comment]
errrr,  sorry about that. :D
I will fix them, don't worry about it.

**Pull request merged**
