### PR TITLE
test refactoring

### PR DESCRIPTION
**Pull request by dafeizizhu**
@fuqcool

### CODE REVIEW

**Comment by fuqcool** [comment]
Can you kill /test/config and mv tests under /test ?
@dafeizizhu

**Comment by fuqcool** [comment]
Well, maybe we don't need to check for id.
If we check for other properties and they passed, we should be confident that this is the object we want to get.

Does it make sense?

**Comment by dafeizizhu** [comment]
make sense. the old test cases do not need modify, the new one can ignore the id assertion.

and what do you mean 'mv tests under /test', making a new directory under the root named 'test' and make a directory under the 'test' named 'tests'? i don't really know what do you mean to do...

**Comment by fuqcool** [comment]
Never mind. I will merge it.

**Pull request merged**
