### PR TITLE
add sign up page

### PR DESCRIPTION
**Pull request by dafeizizhu**
see this url: http://host:port/sign-up

some questions about the front-end:
1. login is using `POST /api/auth`. how about registering? I temporary use `PUT /api/auth` to create a user. It seems not obey the restful rules...
2. how to seperate the page which need login in or not? I see a `if ... else` in the `/public/js/routes/index.js`, maybe it should have something like a filter before routing?

### CODE REVIEW

**Comment by fuqcool** [comment]
I think it make sense to use post /users

**Comment by fuqcool** [comment]
Why send two passwords to the server?

**Comment by dafeizizhu** [comment]
add a route name 'user' and the code is in the '/lib/routes/auth.js' or create a new file to do the crud of users?

**Comment by dafeizizhu** [comment]
let the server do the validation again. just remove it if you want.

**Comment by fuqcool** [comment]
- `/routes/user.js` is there already, just use it
- I don't think server need to validate password again

**Pull request merged**
