### PR TITLE
Models

### PR DESCRIPTION
**Pull request by BohanHsu**
add user_in_game and click, add isAdmin in user model

### CODE REVIEW

**Comment by fuqcool** [comment]
Can you explain why we need ipAddress? 
Also, we won't have gameToken in this version. Can you pls remove it?
@BohanHsu

**Comment by BohanHsu** [comment]
ipAddress is for 2 concern:
1) it is used for fraud detection.
2) it help us know user's location
GameToken is also for security concern, I can remove it temporarily. But we need to bring it back someday I think. 
btw How to reply u?
@fuqcool

**Comment by fuqcool** [comment]
If so, remove them for now, and add them when we need to.

As far as I know, You can't reply to a comment.

**Comment by fuqcool** [comment]
@BohanHsu Please confirm.

**Pull request merged**
